---
path: github.com/mediocregopher/hyrax
deps:
    - loc: https://github.com/mediocregopher/radix.git
      type: git
      ref: d4347b079a16213c138623227b6be4559b69da23
      path: github.com/fzzy/radix

    - loc: https://github.com/grooveshark/golib.git
      type: git
      ref: v0.1.0
      path: github.com/grooveshark/golib

    - loc: https://github.com/mediocregopher/flagconfig.git
      type: git
      ref: v0.4.2
      path: github.com/mediocregopher/flagconfig

    - loc: https://github.com/mediocregopher/manatcp.git
      type: git
      ref: v0.2.1
      path: github.com/mediocregopher/manatcp
