path: github.com/mediocregopher/hyrax
deps:
    - loc: https://github.com/mediocregopher/radix.git
      type: git
      ref: d4347b079a16213c138623227b6be4559b69da23
      path: github.com/fzzy/radix

    - loc: https://github.com/mediocregopher/ghost.git
      type: git
      ref: v0.3.1
      path: github.com/mediocregopher/ghost

    - loc: https://github.com/mediocregopher/flagconfig.git
      type: git
      ref: v0.4.1
      path: github.com/mediocregopher/flagconfig

    - loc: https://github.com/mediocregopher/gojson.git
      type: git
      ref: v0.0.0
      path: github.com/mediocregopher/gojson
